name: dompet_digital
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  permission_handler: ^8.1.6
  font_awesome_flutter: ^9.1.0
  flutter_svg: ^1.0.3
  image_picker: ^0.8.3+4
  # firebase_ml_vision: ^0.12.0
  camera: ^0.10.5+5
  google_mlkit_text_recognition: ^0.11.0
  google_ml_kit: ^0.16.3
  nik_validator: ^1.1.2
  provider: ^6.1.1
  flutter_exif_rotation: ^0.5.1
  image: 3.1.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  google_sign_in_web: ^0.12.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
